// Generated by `npm run db:types` (supabase gen types typescript --local).
// Do not edit by hand: regenerate after every migration and commit the result
// so tsc and the adapter see the same schema the database has.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      item_assignees: {
        Row: {
          item_id: string
          project_id: string
          user_id: string
        }
        Insert: {
          item_id: string
          project_id: string
          user_id: string
        }
        Update: {
          item_id?: string
          project_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_assignees_item_fkey"
            columns: ["item_id", "project_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id", "project_id"]
          },
          {
            foreignKeyName: "item_assignees_membership_fkey"
            columns: ["project_id", "user_id"]
            isOneToOne: false
            referencedRelation: "project_memberships"
            referencedColumns: ["project_id", "user_id"]
          },
        ]
      }
      items: {
        Row: {
          assignee_id: string | null
          created_at: string
          due_date: string | null
          id: string
          name: string
          name_search: string | null
          position: string
          priority: Database["public"]["Enums"]["item_priority"]
          project_id: string
          status: Database["public"]["Enums"]["item_status"]
          updated_at: string
          user_id: string | null
          version: number
        }
        Insert: {
          assignee_id?: string | null
          created_at?: string
          due_date?: string | null
          id?: string
          name: string
          name_search?: string | null
          position?: string
          priority?: Database["public"]["Enums"]["item_priority"]
          project_id: string
          status?: Database["public"]["Enums"]["item_status"]
          updated_at?: string
          user_id?: string | null
          version?: number
        }
        Update: {
          assignee_id?: string | null
          created_at?: string
          due_date?: string | null
          id?: string
          name?: string
          name_search?: string | null
          position?: string
          priority?: Database["public"]["Enums"]["item_priority"]
          project_id?: string
          status?: Database["public"]["Enums"]["item_status"]
          updated_at?: string
          user_id?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "items_assignee_membership_fkey"
            columns: ["project_id", "assignee_id"]
            isOneToOne: false
            referencedRelation: "project_memberships"
            referencedColumns: ["project_id", "user_id"]
          },
          {
            foreignKeyName: "items_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          event_id: string
          id: string
          invitation_id: string | null
          item_id: string | null
          kind: string
          project_id: string | null
          read_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          id?: string
          invitation_id?: string | null
          item_id?: string | null
          kind: string
          project_id?: string | null
          read_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          id?: string
          invitation_id?: string | null
          item_id?: string | null
          kind?: string
          project_id?: string | null
          read_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: true
            referencedRelation: "processed_events"
            referencedColumns: ["event_id"]
          },
          {
            foreignKeyName: "notifications_invitation_id_fkey"
            columns: ["invitation_id"]
            isOneToOne: false
            referencedRelation: "project_invitations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      outbox: {
        Row: {
          created_at: string
          id: string
          name: string
          occurred_at: string
          payload: Json
          published_at: string | null
        }
        Insert: {
          created_at?: string
          id: string
          name: string
          occurred_at: string
          payload: Json
          published_at?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          occurred_at?: string
          payload?: Json
          published_at?: string | null
        }
        Relationships: []
      }
      processed_events: {
        Row: {
          event_id: string
          processed_at: string
        }
        Insert: {
          event_id: string
          processed_at?: string
        }
        Update: {
          event_id?: string
          processed_at?: string
        }
        Relationships: []
      }
      project_invitations: {
        Row: {
          answered_at: string | null
          created_at: string
          id: string
          invited_by: string
          invitee_id: string
          project_id: string
          status: string
        }
        Insert: {
          answered_at?: string | null
          created_at?: string
          id: string
          invited_by: string
          invitee_id: string
          project_id: string
          status: string
        }
        Update: {
          answered_at?: string | null
          created_at?: string
          id?: string
          invited_by?: string
          invitee_id?: string
          project_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_invitations_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_invitations_invitee_id_fkey"
            columns: ["invitee_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_invitations_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_memberships: {
        Row: {
          created_at: string
          project_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          project_id: string
          role: string
          user_id: string
        }
        Update: {
          created_at?: string
          project_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_memberships_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          created_at: string
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          created_at: string
          email: string
          id: string
          policy_accepted_at: string | null
          policy_version: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          policy_accepted_at?: string | null
          policy_version?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          policy_accepted_at?: string | null
          policy_version?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_member_with_event: {
        Args: {
          p_event_id: string
          p_event_name: string
          p_occurred_at: string
          p_payload: Json
          p_project_id: string
          p_user_id: string
        }
        Returns: boolean
      }
      create_item_with_event: {
        Args: {
          p_assignee_ids?: string[]
          p_due_date: string
          p_event_id: string
          p_event_name: string
          p_item_id: string
          p_name: string
          p_occurred_at: string
          p_payload: Json
          p_priority: Database["public"]["Enums"]["item_priority"]
          p_project_id: string
          p_user_id: string
        }
        Returns: undefined
      }
      create_project_for_owner: {
        Args: { p_name: string; p_project_id: string; p_user_id: string }
        Returns: undefined
      }
      erase_account: { Args: { p_user_id: string }; Returns: undefined }
      immutable_unaccent: { Args: { "": string }; Returns: string }
      invite_member_with_event: {
        Args: {
          p_event_id: string
          p_event_name: string
          p_invitation_id: string
          p_invited_by: string
          p_invitee_id: string
          p_occurred_at: string
          p_payload: Json
          p_project_id: string
        }
        Returns: string
      }
      mark_notification_read: {
        Args: { p_account_id: string; p_id: string }
        Returns: boolean
      }
      record_invitation_notification: {
        Args: {
          p_event_id: string
          p_invitation_id: string
          p_project_id: string
          p_user_id: string
        }
        Returns: boolean
      }
      record_item_created_notification: {
        Args: { p_event_id: string; p_item_id: string; p_user_id: string }
        Returns: boolean
      }
      record_member_added_notification: {
        Args: { p_event_id: string; p_project_id: string; p_user_id: string }
        Returns: boolean
      }
      remove_project_member: {
        Args: { p_caller_id: string; p_member_id: string; p_project_id: string }
        Returns: string
      }
      respond_to_invitation: {
        Args: {
          p_accept: boolean
          p_invitation_id: string
          p_invitee_id: string
        }
        Returns: string
      }
      set_item_assignees: {
        Args: {
          p_assignee_ids: string[]
          p_item_id: string
          p_project_id: string
        }
        Returns: undefined
      }
      swap_item_position: {
        Args: {
          p_expected_version: number
          p_item_id: string
          p_position: string
          p_project_id: string
        }
        Returns: {
          assignee_id: string | null
          created_at: string
          due_date: string | null
          id: string
          name: string
          name_search: string | null
          position: string
          priority: Database["public"]["Enums"]["item_priority"]
          project_id: string
          status: Database["public"]["Enums"]["item_status"]
          updated_at: string
          user_id: string
          version: number
        }
        SetofOptions: {
          from: "*"
          to: "items"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      unaccent: { Args: { "": string }; Returns: string }
      uuid_generate_v7: { Args: never; Returns: string }
    }
    Enums: {
      item_priority: "low" | "normal" | "high"
      item_status: "todo" | "doing" | "done"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      item_priority: ["low", "normal", "high"],
      item_status: ["todo", "doing", "done"],
    },
  },
} as const

