// Regenerates packages/infra/src/database.types.ts from the running local
// database and prepends a header so the file explains itself. Run it after every
// migration and commit the result.
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const OUT = 'packages/infra/src/database.types.ts';
const HEADER =
    '// Generated by `npm run db:types` (supabase gen types typescript --local).\n' +
    '// Do not edit by hand: regenerate after every migration and commit the result\n' +
    '// so tsc and the adapter see the same schema the database has.\n\n';

const body = execFileSync('supabase', ['gen', 'types', 'typescript', '--local'], {
    encoding: 'utf8',
});

writeFileSync(OUT, HEADER + body);
console.log(`wrote ${OUT}`);
